#!/usr/bin/env python
"""
przeglad_tlumaczen.py — wspólny helper trybu ``--draft`` autotłumaczy.

Oba buildery (`buduj_wielojezyczne_ui.py`, `buduj_wielojezyczne_docs.py`)
w trybie roboczym (`--draft`) zamiast kanonicznego nagłówka „NIE edytuj
ręcznie" wstrzykują NEUTRALNY nagłówek zachęcający do edycji oraz emitują
plik-towarzysz z checklistą przeglądu halucynacji. Cel: paczka kontrybucji
języka, którą maintainer wysyła osobie trzeciej / agentowi do recenzji —
recenzent bez naszej konstytucji/pamięci NIE może dostać sprzecznego rozkazu
(„plik wygenerowany automatycznie, nie edytuj") dokładnie wtedy, gdy chcemy,
żeby halucynacje poprawił.

Decyzja architektoniczna (2026-06-11, ścieżka D bez D3): paczka end-usera
zostaje czysta (v17.0 — szablony docs i dev-skrypty NIE wchodzą do bundla);
ulepszamy WYŁĄCZNIE tooling maintainera odpalany ze źródła. Ten moduł jest
dev-toolem (jak build_release / generuj_dokumentacje) — NIE importuje
`sciezki`, chodzi tylko ze źródła przez `Path(__file__).parent`.

Checklist celowo PO ANGIELSKU — spójnie z konwencją „cała infrastruktura
kontrybutorska mówi po angielsku, zerowy próg dla zagranicznych kontrybutorów"
(patrz nagłówki build_release.py od 13.1). Recenzent włoskiego/islandzkiego
docs to zwykle native danego języka albo agent — angielski jest najmniej
wykluczający. Hotspoty zaczerpnięte z [[reguly_tlumaczen]] (podświadomość agenta).
"""
from __future__ import annotations

from pathlib import Path


def naglowek_roboczy(sciezka_rel: str, zrodlo_rel: str, narzedzie: str) -> str:
    """Neutralny nagłówek YAML dla pliku-draftu (zachęca do edycji).

    Args:
        sciezka_rel: ścieżka wynikowa względem roota repo, np.
            ``dictionaries/it/gui/dokumentacja/manual.yaml``.
        zrodlo_rel: ścieżka źródła PL względem roota, np.
            ``dictionaries/pl/gui/dokumentacja/manual.yaml``.
        narzedzie: nazwa skryptu-generatora (do treści nagłówka).

    Zwraca blok komentarzy `#` zakończony pustą linią — drop-in zamiennik
    kanonicznego nagłówka „NIE edytuj ręcznie" w obu builderach.

    Treść PO ANGIELSKU — recenzentem draftu bywa nie-polskojęzyczny kontrybutor
    lub agent; polski nagłówek byłby dla niego barierą (spójnie z konwencją
    „cała infra kontrybutorska mówi po angielsku" i z checklistą poniżej).
    """
    return (
        "# =============================================================================\n"
        f"# {sciezka_rel}\n"
        "#\n"
        "# ⚠ WORKING DRAFT FOR REVIEW — preliminary machine translation.\n"
        f"# Generated by `{narzedzie} --draft` from {zrodlo_rel} (Polish source).\n"
        "#\n"
        "# You MAY and SHOULD edit this file by hand: fix hallucinations, language\n"
        "# calques and inconsistencies against the Polish source. This is NOT the\n"
        "# final version — it exists for review before inclusion in a release.\n"
        "# (After approval the maintainer regenerates it without --draft, which\n"
        "# restores the canonical \"do not edit by hand\" header.)\n"
        "#\n"
        "# Keep 1:1 (do NOT translate): placeholders {key}, file/folder names\n"
        "# (skrypty/, opowiesci/, runtime/), extensions, the brand \"Reżyser Audio GPT\",\n"
        "# proper names (voices, Vocalizer, Tiflotecnia…) and version numbers.\n"
        "# Full review checklist: skrypty/przeglad_<tool>.md\n"
        "# =============================================================================\n"
        "\n"
    )


# Wspólny rdzeń checklisty (reguły niezależne od typu pliku).
_CHECKLIST_WSPOLNA = """\
## Keep these 1:1 — do NOT translate or alter

- `{curly_placeholders}` — copy verbatim, including the braces. Same multiset
  in the translation as in the Polish source.
- File/folder names and extensions: `skrypty/`, `opowiesci/`, `runtime/`,
  `.txt`, `.md`, `.yaml`. Never localize a path to a native word
  (`historias/`, `sögur/`, `script/` are BUGS — must stay `opowiesci/` etc.).
- The product brand "Reżyser Audio GPT" stays as-is in every language.
- Proper names: voices and engines (Vocalizer, Tiflotecnia, Cerrence,
  Eloquence, Samantha, Alice, Milena, …) and version numbers (e.g. 17.2.2).

## Names that must come from the engine, not the model's imagination

- CIPHER NAMES: take the label from
  `dictionaries/<code>/szyfry/<id>.yaml::etykieta` — never invent a descriptive
  one. The "Jąkanie" (stutter) cipher is it "Balbuzie", es "Tartamudeo" — NOT
  `inceppamento` / `cortes` (= a mechanism jamming). When in doubt, open the file.
- HARDCODED UI TAGS: `[CEL SCENY]` and `[ODRZUCENIE_AI]` are emitted VERBATIM by
  the Python engine in every language. Keep them 1:1 — do NOT translate to
  `[SCENE GOAL]` etc.; the user would search for a tag the engine never produces.

## Common calques — use the NATIVE term, never the literal

These slip past automatic leak detection (no Polish characters), yet they are
mistranslations. For each, pick the native target-language term — do NOT calque
from PL/EN. Canon (de / es / fr / it / ru):

| concept (PL) | de | es | fr | it | ru |
|---|---|---|---|---|---|
| wizard (kreator) | Assistent | asistente | assistant | procedura guidata | мастер |
| Python dict (mapy) | Dictionaries | diccionarios | mappages | mappe | словари |
| wire up code (okablować) | eingebunden | integrado | intégré | integrato | — |
| release suffix ("Wersja Wydawnicza") | Release-Version | Versión de Lanzamiento | Version de Lancement | Versione di Rilascio | Релизная версия |
| screen reader (czytnik ekranu) | Screenreader | lector de pantalla | lecteur d'écran | lettore di schermo | скринридер |

- "mapy" here means a Python dict → NEVER ru `карты` / de `Karten` (= playing
  cards / geographic maps). NEVER es `mapas` (use `diccionarios`).
- "kreator" is a wizard → NEVER `создатель` / `creatore` / `Schöpfer` / `creator`
  (= a creator/God).
- For the app-version suffix translate ONLY the suffix and keep
  `{numer_wersji} – ` unchanged — NEVER ru `Издательская` / it `di Pubblicazione`
  (= "for a book publisher").
"""

_CHECKLIST_DOCS = """\
## Documentation hotspots (manual / dictionaries / tales templates)

- FIRST LINE / TITLE must be in the target language — never leave a Polish
  title (`Podręcznik`, `Reżyser`, `Kompletny…`). A Polish first line is a leak.
- INVENTED SECTIONS: if a translated section is noticeably longer than the
  Polish source (rule of thumb: > 1.5×), the model probably bolted on an extra
  chapter. Compare against the PL source and delete anything with no PL counterpart.
- CAESAR CIPHER: the alphabet string and its character count MUST match THIS
  language's `dictionaries/<code>/podstawy.yaml` alphabet — do NOT blindly copy
  the Polish "35 chars / AĄBCĆ…". English = 26, Italian = 21, Russian uses
  Cyrillic, etc.
- TIPOGLICEMIA (scrambled-letters demo): the example sentence must STAY
  scrambled (inner letters shuffled). If it reads as grammatically correct
  prose, the effect was lost — re-scramble it natively.
- TERMINOLOGY CONSISTENCY: pick ONE native word for recurring terms (e.g. the
  "vial"/fiolka) and use it across every section and file in the pack.
- META-INSTRUCTION SKIP: for prompt-like passages ("You are a narrative
  engine…"), make sure the FIRST paragraph was actually translated — models
  tend to leave the opening lines in the source language, reading them as
  instructions to themselves instead of data.
- STEP HEADERS: section openers "KROK <n>:" must be localized to the native
  step word (de SCHRITT, es PASO, fr ÉTAPE, fi VAIHE, is SKREF, it PASSO,
  ru ШАГ). Models often leave "KROK" untranslated, treating it as a marker.
- ALGORITHM EXAMPLES must match the ENGINE, not intuition or another language.
  When you localize the example word in a cipher demo (e.g. the stutter cipher),
  RE-COMPUTE the output against the actual rule — a different native word can
  have a different second letter and break the very rule the example illustrates.
- INFLECTED LANGUAGES (Icelandic, Finnish): the machine output frequently gets
  the grammatical CASE/gender wrong (case is NOT frozen the way {placeholders}
  are). For is/fi a second, independent native/AI reviewer focused purely on
  declension is worth it — anchor every form to one already in the file.
"""

_CHECKLIST_UI = """\
## UI hotspots (ui.yaml)

- MENU ACCELERATOR `&`: exactly one per label, same count as the source. Move
  it onto a sensible letter of the TARGET-language word (do not just keep the
  Polish position).
- KEYBOARD SHORTCUTS `\\tCtrl+...`, `Alt`, `Shift`, `Cmd`: keep verbatim. Never
  localize modifier names.
- PATHS IN TOOLTIPS/MESSAGES: folder references (`skrypty/`, `runtime/skrypty/`,
  `opowiesci/`) must stay literal — the folder on disk is not localized.
- BUTTON-NAME CITATIONS: avoid quoting a literal button label inside a message;
  describe the action instead (future-proof + no hallucinated label).
- TOOLTIP vs LABEL are SEPARATE keys for the same control — translate both.
"""


def _formatuj_leaki(leaki_per_plik) -> str:
    """Formatuje wykryte PL-leaki (post-processor `audyt_leakow`) jako appendix.

    `leaki_per_plik`: ``{(kod, plik): {sekcja: [Leak, ...]}}``. NIE importujemy
    tu `audyt_leakow` — obiekty Leak są kacze-typowane po atrybutach
    (`linia_nr`, `powod`, `tekst`), więc moduł zostaje wolny od `lingua`.

    Detektor ŚWIADOMIE over-reportuje (dydaktyczne „ą ę ł", nazwy własne,
    linie z alfabetem → false-positive lingua), dlatego appendix triażuje po
    klasie powodu i jawnie ostrzega recenzenta. Zwraca "" gdy brak leaków.
    """
    if not leaki_per_plik:
        return ""
    bloki: list[str] = []
    for kod, plik in sorted(leaki_per_plik):
        per_sekcja = leaki_per_plik[(kod, plik)]
        prawdopodobne: list[str] = []
        mozliwe: list[str] = []
        for sekcja in sorted(per_sekcja):
            for l in per_sekcja[sekcja]:
                klasa = l.powod.split(":", 1)[0]
                wiersz = f"  - `{sekcja}` L{l.linia_nr} [{l.powod}]: {l.tekst}"
                (mozliwe if klasa == "znak-PL" else prawdopodobne).append(wiersz)
        if not prawdopodobne and not mozliwe:
            continue
        czesci = [f"### `{kod}` / {plik}"]
        if prawdopodobne:
            czesci.append("- LIKELY (whole-line drift / known Polish module name) — verify & translate:")
            czesci.extend(prawdopodobne)
        if mozliwe:
            czesci.append("- POSSIBLE (stray Polish characters — OFTEN a false positive):")
            czesci.extend(mozliwe)
        bloki.append("\n".join(czesci))
    if not bloki:
        return ""
    return (
        "## Auto-detected Polish-leak candidates (audyt_leakow)\n\n"
        "These lines were flagged AUTOMATICALLY after translation. This is a FUNNEL,\n"
        "not a verdict — the detector over-reports. Triage each one:\n\n"
        "- **LIKELY** rows (a whole line drifted back to Polish, or a known Polish\n"
        "  module name slipped through: „Reżyser\", „Poliglota\", „Księga Świata\",\n"
        "  „KROK\") are probably real — translate / inflect them.\n"
        "- **POSSIBLE** rows (stray Polish characters) are OFTEN FALSE POSITIVES:\n"
        "  Polish letters legitimately appear in didactic alphabet demos (ą, ę, ł),\n"
        "  in proper nouns (place names) and in cipher illustrations. Skip those.\n\n"
        "If you do NOT read Polish: paste a flagged fragment into a translator or a\n"
        "chatbot to decide whether it is stray Polish prose (fix it) or an intended\n"
        "literal (leave it). Line numbers are relative to the section's text.\n\n"
        + "\n\n".join(bloki)
        + "\n\n"
    )


def _tekst_promptu(
    narzedzie: str,
    wytworzone: list[tuple[str, str]],
    leaki_per_plik=None,
) -> str:
    """Składa treść markdown checklisty przeglądu."""
    # Grupuj wytworzone drafty per język dla czytelnej listy.
    per_jezyk: dict[str, list[str]] = {}
    for kod, plik in wytworzone:
        per_jezyk.setdefault(kod, []).append(plik)

    linie_plikow: list[str] = []
    for kod in sorted(per_jezyk):
        pliki = ", ".join(sorted(per_jezyk[kod]))
        linie_plikow.append(f"- `{kod}`: {pliki}")
    lista_plikow = "\n".join(linie_plikow) if linie_plikow else "- (none)"

    hotspoty = _CHECKLIST_DOCS if narzedzie.endswith("docs.py") else _CHECKLIST_UI

    return (
        f"# Translation review — draft batch from `{narzedzie} --draft`\n\n"
        "These files are MACHINE-TRANSLATED DRAFTS, not final. You are explicitly\n"
        "expected to EDIT them: fix mistranslations, calques and inconsistencies\n"
        "against the Polish source, then return the corrected files. The draft\n"
        "header inside each file says the same — ignore any \"do not edit\" wording\n"
        "you may know from canonical generated files; it does not apply here.\n\n"
        "## Draft files produced in this run\n\n"
        f"{lista_plikow}\n\n"
        "Compare each against its Polish source under\n"
        "`dictionaries/pl/gui/...` (same relative path, `pl` swapped in).\n\n"
        f"{_CHECKLIST_WSPOLNA}\n"
        f"{hotspoty}\n"
        f"{_formatuj_leaki(leaki_per_plik)}"
        "## How to return\n\n"
        "Edit the draft files in place and send them back. Do not touch the\n"
        "Polish source. When in doubt about a native idiom, leave a `# REVIEW:`\n"
        "comment rather than guessing.\n"
    )


def zapisz_prompt_przegladu(
    narzedzie: str,
    wytworzone: list[tuple[str, str]],
    root: Path,
    leaki_per_plik=None,
) -> Path | None:
    """Zapisuje checklistę przeglądu do ``skrypty/przeglad_<rdzen>.md``.

    Args:
        narzedzie: nazwa skryptu-generatora (np. ``buduj_wielojezyczne_docs.py``).
        wytworzone: lista par ``(kod_jezyka, nazwa_pliku)`` draftów z tego runu.
        root: katalog bazowy repo (``Path(__file__).parent`` buildera).
        leaki_per_plik: opcjonalnie ``{(kod, plik): {sekcja: [Leak]}}`` z
            post-processora ``audyt_leakow`` (builder docs liczy i przekazuje
            jako dane — patrz ``_formatuj_leaki``). UI woła bez tego argumentu.

    Returns:
        Ścieżkę zapisanego pliku, albo ``None`` gdy nic nie wytworzono lub
        zapis się nie powiódł (emisja checklisty to wygoda, nie część krytyczna —
        fail open, nie wywracamy buildu tłumaczeń).
    """
    if not wytworzone:
        return None
    # rdzeń nazwy: buduj_wielojezyczne_docs.py → docs, *_ui.py → ui
    rdzen = "docs" if narzedzie.endswith("docs.py") else "ui"
    katalog = root / "skrypty"
    cel = katalog / f"przeglad_{rdzen}.md"
    try:
        katalog.mkdir(parents=True, exist_ok=True)
        cel.write_text(
            _tekst_promptu(narzedzie, wytworzone, leaki_per_plik),
            encoding="utf-8",
        )
    except OSError:
        return None
    return cel
